;;; Createa apackage and move to it
(defpackage #:movies
  (:use #:cl #:proto-graph #:proto-query))

(in-package #:movies)

(defvar *movie*)
(defvar *node*)

;;; Defining Star Wars

(setf *movie* (node-create :label :movie :properties '(:name "Star Wars")))
(setf *node* (node-create :label :person :properties '(:name "Mark" :surname "Hamill")))
(link-create :acted-on *node* *movie* :properties '(:plays "Luke Skywalker"))
(setf *node* (node-create :label :person :properties '(:name "Harrison" :surname "Ford")))
(link-create :acted-on *node* *movie* :properties '(:plays "Han Solo"))
(setf *node* (node-create :label :person :properties '(:name "Carrie" :surname "Fisher")))
(link-create :acted-on *node* *movie* :properties '(:plays "Princess Leia Organa"))
(setf *node* (node-create :label :person :properties '(:name "Peter" :surname "Cushing")))
(link-create :acted-on *node* *movie* :properties '(:plays "Grand Moff Tarkin"))
(setf *node* (node-create :label :person :properties '(:name "Alec" :surname "Guinness")))
(link-create :acted-on *node* *movie* :properties '(:plays "Ben Obi-Wan Kenobi"))
(setf *node* (node-create :label :person :properties '(:name "Anthony" :surname "Daniels")))
(link-create :acted-on *node* *movie* :properties '(:plays "C-3PO"))
(setf *node* (node-create :label :person :properties '(:name "Kenny" :surname "Baker")))
(link-create :acted-on *node* *movie* :properties '(:plays "R2-D2"))
(setf *node* (node-create :label :person :properties '(:name "Peter" :surname "Mayhew")))
(link-create :acted-on *node* *movie* :properties '(:plays "Chewbacca"))
(setf *node* (node-create :label :person :properties '(:name "David" :surname "Prowse")))
(link-create :acted-on *node* *movie* :properties '(:plays "Darth Vader"))
(setf *node* (node-create :label :person :properties '(:name "Phil" :surname "Brown")))
(link-create :acted-on *node* *movie* :properties '(:plays "Uncle Owen"))
(setf *node* (node-create :label :person :properties '(:name "Shelagh" :surname "Fraser")))
(link-create :acted-on *node* *movie* :properties '(:plays "Aunt Beru"))
(setf *node* (node-create :label :person :properties '(:name "Jack" :surname "Purvis")))
(link-create :acted-on *node* *movie* :properties '(:plays "Chief Jawa"))
(setf *node* (node-create :label :person :properties '(:name "Alex" :surname "McCrindle")))
(link-create :acted-on *node* *movie* :properties '(:plays "General Dodonna"))
(setf *node* (node-create :label :person :properties '(:name "Eddie" :surname "Byrne")))
(link-create :acted-on *node* *movie* :properties '(:plays "General Willard"))
(setf *node* (node-create :label :person :properties '(:name "Drewe" :surname "Henley")))
(link-create :acted-on *node* *movie* :properties '(:plays "Red Leader"))
(setf *node* (node-create :label :person :properties '(:name "George" :surname "Lucas")))
(link-create :directed *node* *movie*)
(link-create :wrote ** *movie*)

;;; Defining Raiders of the Lost Ark

(setf *movie* (node-create :label :movie :properties '(:name "Raiders of the Lost Ark")))
(setf *node* (car (node-match :label :person :properties '(:name "Harrison" :surname "Ford"))))
(link-create :acted-on *node* *movie* :properties '(:plays "Indy"))
(setf *node* (node-create :label :person :properties '(:name "Karen" :surname "Allen")))
(link-create :acted-on *node* *movie* :properties '(:plays "Marion Ravenwood"))
(setf *node* (node-create :label :person :properties '(:name "Paul" :surname "Freeman")))
(link-create :acted-on *node* *movie* :properties '(:plays "Dr. René Belloq"))
(setf *node* (node-create :label :person :properties '(:name "Ronald" :surname "Lacey")))
(link-create :acted-on *node* *movie* :properties '(:plays "Major Arnold Toht"))
(setf *node* (node-create :label :person :properties '(:name "John" :surname "Rhys-Davies")))
(link-create :acted-on *node* *movie* :properties '(:plays "Sallah"))
(setf *node* (node-create :label :person :properties '(:name "Denholm" :surname "Elliott")))
(link-create :acted-on *node* *movie* :properties '(:plays "Dr. Marcus Brody"))
(setf *node* (node-create :label :person :properties '(:name "Alfred" :surname "Molina")))
(link-create :acted-on *node* *movie* :properties '(:plays "Satipo"))
(setf *node* (node-create :label :person :properties '(:name "Wolf" :surname "Kahler")))
(link-create :acted-on *node* *movie* :properties '(:plays "Colonel Dietrich"))
(setf *node* (node-create :label :person :properties '(:name "Anthony" :surname "Higgins")))
(link-create :acted-on *node* *movie* :properties '(:plays "Gobler"))
(setf *node* (node-create :label :person :properties '(:name "Vic" :surname "Tablian")))
(link-create :acted-on *node* *movie* :properties '(:plays "Barranca / Monkey Man"))
(setf *node* (node-create :label :person :properties '(:name "Don" :surname "Fellows")))
(link-create :acted-on *node* *movie* :properties '(:plays "Col. Musgrove"))
(setf *node* (node-create :label :person :properties '(:name "William" :surname "Hootkins")))
(link-create :acted-on *node* *movie* :properties '(:plays "Major Eaton"))
(setf *node* (node-create :label :person :properties '(:name "Bill" :surname "Reimbold")))
(link-create :acted-on *node* *movie* :properties '(:plays "Bureaucrat"))
(setf *node* (node-create :label :person :properties '(:name "Fred" :surname "Sorenson")))
(link-create :acted-on *node* *movie* :properties '(:plays "Jock"))
(setf *node* (node-create :label :person :properties '(:name "Patrick" :surname "Durkin")))
(link-create :acted-on *node* *movie* :properties '(:plays "Australian Climber"))
(setf *node* (node-create :label :person :properties '(:name "Steven" :surname "Spielberg")))
(link-create :directed *node* *movie*)
(setf *node* (car (node-match :label :person :properties '(:name "George" :surname "Lucas"))))
(link-create :wrote *node* *movie* :properties '(:wrote "Story"))
(setf *node* (node-create :label :person :properties '(:name "Philip" :surname "Kaufman")))
(link-create :wrote *node* *movie* :properties '(:wrote "Story"))
(setf *node* (node-create :label :person :properties '(:name "Lawrence" :surname "Kasdan")))
(link-create :wrote *node* *movie* :properties '(:wrote "Screenplay"))
